[project]
site_url = "https://www.manojitnath.com/"
site_name = "Manojit"
site_description = "Manojit's technical blog & knowledge base"
site_author = "Manojit Nath"
copyright = "Copyright &copy; 2026 manojitnath"
# repo_url = "https://github.com/manojitnath"
# repo_name = "GitHub"
# edit_uri = "edit/main/docs/"

# --------nav start------
nav = [

  # Home-page nav
  { "Home" = [
    { "Overview" = "index.md" },
  ]},

  # Blog-page nav
  { "Blog" = ["blog/index.md"] },

  # Foundation-page nav
  { "Foundations" = [
    { "Foundations" = "foundations/index.md" },
    { "Linux" = [
        "foundations/linux/index.md",  # If navigation.indexes is ON
        { "Basics & Files" = "foundations/linux/01-basics-and-files.md" },
        { "Users & Processes" = "foundations/linux/02-users-and-processes.md" },
        { "Admin & Networks" = "foundations/linux/03-admin-and-networks.md" },
        { "Automation & Tools" = "foundations/linux/04-automation-and-tools.md" },
    ]},
  ]},

  # Projects-page nav
  { "Projects" = [
  { "Projects" = "projects/index.md" },  
    { "Linux" = [
      { "Secure a Linux Server" = "projects/linux/secure-a-linux-server.md" },
      { "Setup Web & DNS" = "projects/linux/setup-web-and-dns.md" },
      ]},
  ]},

  # About Me-page nav
  { "About me" = [
   { "Hello" = "about/about-me.md" },
   { "Resume" = "about/resume.md" },
  ]},
] 
# --------nav end------

extra_css = [
  "stylesheets/style.css",
  "stylesheets/custom.css" 
]

# extra_javascript = ["javascripts/extra.js"]

[project.theme]
# variant = "classic"
custom_dir = "overrides"
favicon = "images/favicon.png"
language = "en"
features = [
  "announce.dismiss",
  # "content.action.edit",
  # "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  # "navigation.expand",
  "navigation.footer",
  # "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  # "navigation.prune",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "toc.follow",
  # "toc.integrate",
]
[project.theme.icon]
repo = "fontawesome/brands/github"
logo = "lucide/bot"

# [project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

# 1. Light Mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# 2. Dark Mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "blue"
accent = "cyan"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"


[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/manojitnath"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/manojitnath/"

# [[project.extra.social]]
# icon = "fontawesome/brands/mastodon"
# link = "https://fosstodon.org/@user"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc.permalink = true
pymdownx.arithmatex.generic = true
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets.base_path = "includes"
pymdownx.superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
pymdownx.tabbed.alternate_style = true
pymdownx.tabbed.combine_header_slug = true
pymdownx.tasklist.custom_checkbox = true
pymdownx.tilde = {}

[[project.markdown_extensions.zensical.extensions.preview.configurations]]
targets.include = [
  "customization.md",
  "compatibility/markdown/*",
]

[project.plugins.blog]

[project.plugins.tags]

[project.extra.tags]
default = "lucide/hash"

[project.extra]
generator = false